version: '3.8'

networks:
  funnytgbot_net:
    driver: bridge

services:
  funnytgbot:
    build: ../
    container_name: funnytgbot
    restart: always
    ports:
      - 7001:7001
    networks:
      - funnytgbot_net
    environment:
      TG_TOKEN: yourTgBotTocken
      MONGO_CONN_STRING: yourMongoDbAddr
    depends_on:
      - mongo-db

  mongo-db:
        container_name: mongo-db
        restart: always
        ports:
            - '27020:27017'
        networks:
          - funnytgbot_net
        logging:
            options:
                max-size: 1g
        image: mongo